#pragma once

#include <string>

enum class TokenKind {
    EndOfFile,
    Identifier,
    Number,
    StringLiteral,
    KeywordStruct,
    KeywordChar,
    KeywordShort,
    KeywordInt,
    KeywordLong,
    KeywordVoid,
    KeywordExtern,
    KeywordReturn,
    KeywordIf,
    KeywordElse,
    KeywordWhile,
    KeywordFor,
    KeywordBreak,
    KeywordContinue,
    KeywordDo,
    KeywordSwitch,
    KeywordCase,
    KeywordDefault,
    KeywordUnsigned,
    KeywordSigned,
    KeywordTypedef,
    KeywordEnum,
    KeywordUnion,
    KeywordConst,
    KeywordVolatile,
    KeywordSizeof,
    KeywordGoto,
    KeywordFloat,
    KeywordDouble,
    KeywordStatic,
    KeywordRestrict,
    KeywordInline,
    KeywordNoreturn,
    KeywordAtomic,
    KeywordAlignas,
    KeywordThreadLocal,
    KeywordStaticAssert,
    KeywordGeneric,
    KeywordAlignof,
    KeywordBool,
    FloatLiteral,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Colon,
    Dot,
    Arrow,
    Semicolon,
    Comma,
    Plus,
    Minus,
    Star,
    Slash,
    Ampersand,
    Equal,
    Bang,
    EqualEqual,
    BangEqual,
    AmpAmp,
    PipePipe,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Percent,
    LessLess,
    GreaterGreater,
    Caret,
    Pipe,
    Tilde,
    PlusPlus,
    MinusMinus,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    LessLessEqual,
    GreaterGreaterEqual,
    AmpEqual,
    CaretEqual,
    PipeEqual,
    Question,
    DotDotDot
};

struct Token {
    TokenKind kind;
    std::string lexeme;
    long long intValue;
    double doubleValue = 0.0;
    std::string stringValue;
    std::string stringPrefix;  // "L", "u8", "u", "U" 或空
    int line;
    int column;
};

const char *tokenKindName(TokenKind kind);
