#include "Token.h"

const char *tokenKindName(TokenKind kind) {
    switch (kind) {
    case TokenKind::EndOfFile:
        return "end of file";
    case TokenKind::Identifier:
        return "identifier";
    case TokenKind::Number:
        return "number";
    case TokenKind::StringLiteral:
        return "string literal";
    case TokenKind::KeywordStruct:
        return "struct";
    case TokenKind::KeywordChar:
        return "char";
    case TokenKind::KeywordShort:
        return "short";
    case TokenKind::KeywordInt:
        return "int";
    case TokenKind::KeywordLong:
        return "long";
    case TokenKind::KeywordVoid:
        return "void";
    case TokenKind::KeywordExtern:
        return "extern";
    case TokenKind::KeywordReturn:
        return "return";
    case TokenKind::KeywordIf:
        return "if";
    case TokenKind::KeywordElse:
        return "else";
    case TokenKind::KeywordWhile:
        return "while";
    case TokenKind::KeywordFor:
        return "for";
    case TokenKind::KeywordBreak:
        return "break";
    case TokenKind::KeywordContinue:
        return "continue";
    case TokenKind::KeywordDo:
        return "do";
    case TokenKind::KeywordSwitch:
        return "switch";
    case TokenKind::KeywordCase:
        return "case";
    case TokenKind::KeywordDefault:
        return "default";
    case TokenKind::KeywordUnsigned:
        return "unsigned";
    case TokenKind::KeywordSigned:
        return "signed";
    case TokenKind::KeywordTypedef:
        return "typedef";
    case TokenKind::KeywordEnum:
        return "enum";
    case TokenKind::KeywordUnion:
        return "union";
    case TokenKind::KeywordConst:
        return "const";
    case TokenKind::KeywordVolatile:
        return "volatile";
    case TokenKind::KeywordSizeof:
        return "sizeof";
    case TokenKind::KeywordGoto:
        return "goto";
    case TokenKind::KeywordFloat:
        return "float";
    case TokenKind::KeywordDouble:
        return "double";
    case TokenKind::KeywordStatic:
        return "static";
    case TokenKind::KeywordRestrict:
        return "restrict";
    case TokenKind::KeywordInline:
        return "inline";
    case TokenKind::KeywordNoreturn:
        return "_Noreturn";
    case TokenKind::KeywordAtomic:
        return "_Atomic";
    case TokenKind::KeywordAlignas:
        return "_Alignas";
    case TokenKind::KeywordThreadLocal:
        return "_Thread_local";
    case TokenKind::KeywordStaticAssert:
        return "_Static_assert";
    case TokenKind::KeywordGeneric:
        return "_Generic";
    case TokenKind::KeywordAlignof:
        return "_Alignof";
    case TokenKind::KeywordBool:
        return "_Bool";
    case TokenKind::FloatLiteral:
        return "float literal";
    case TokenKind::LeftParen:
        return "(";
    case TokenKind::RightParen:
        return ")";
    case TokenKind::LeftBrace:
        return "{";
    case TokenKind::RightBrace:
        return "}";
    case TokenKind::LeftBracket:
        return "[";
    case TokenKind::RightBracket:
        return "]";
    case TokenKind::Colon:
        return ":";
    case TokenKind::Dot:
        return ".";
    case TokenKind::Arrow:
        return "->";
    case TokenKind::Semicolon:
        return ";";
    case TokenKind::Comma:
        return ",";
    case TokenKind::Plus:
        return "+";
    case TokenKind::Minus:
        return "-";
    case TokenKind::Star:
        return "*";
    case TokenKind::Slash:
        return "/";
    case TokenKind::Ampersand:
        return "&";
    case TokenKind::Equal:
        return "=";
    case TokenKind::Bang:
        return "!";
    case TokenKind::EqualEqual:
        return "==";
    case TokenKind::BangEqual:
        return "!=";
    case TokenKind::AmpAmp:
        return "&&";
    case TokenKind::PipePipe:
        return "||";
    case TokenKind::Less:
        return "<";
    case TokenKind::LessEqual:
        return "<=";
    case TokenKind::Greater:
        return ">";
    case TokenKind::GreaterEqual:
        return ">=";
    case TokenKind::Percent:
        return "%";
    case TokenKind::LessLess:
        return "<<";
    case TokenKind::GreaterGreater:
        return ">>";
    case TokenKind::Caret:
        return "^";
    case TokenKind::Pipe:
        return "|";
    case TokenKind::Tilde:
        return "~";
    case TokenKind::PlusPlus:
        return "++";
    case TokenKind::MinusMinus:
        return "--";
    case TokenKind::PlusEqual:
        return "+=";
    case TokenKind::MinusEqual:
        return "-=";
    case TokenKind::StarEqual:
        return "*=";
    case TokenKind::SlashEqual:
        return "/=";
    case TokenKind::PercentEqual:
        return "%=";
    case TokenKind::LessLessEqual:
        return "<<=";
    case TokenKind::GreaterGreaterEqual:
        return ">>=";
    case TokenKind::AmpEqual:
        return "&=";
    case TokenKind::CaretEqual:
        return "^=";
    case TokenKind::PipeEqual:
        return "|=";
    case TokenKind::Question:
        return "?";
    case TokenKind::DotDotDot:
        return "...";
    }

    return "unknown";
}
